# Generated by Django 5.2.1 on 2025-06-09 22:23

import django.db.models.deletion
import titulacion.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('extensiones_aceptados', models.CharField(default='pdf,doc,docx', help_text='Extensiones permitidas separadas por comas (ej: pdf,doc,docx,jpg,png)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('curp', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True, verbose_name='CURP')),
                ('numero_control', models.CharField(max_length=20, unique=True, verbose_name='Número de control')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('primer_apellido', models.CharField(max_length=100, verbose_name='Primer apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo apellido')),
                ('correo', models.EmailField(max_length=255, unique=True, verbose_name='Correo electrónico')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Género')),
                ('usuario_egresado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Egresado',
                'verbose_name_plural': 'Egresados',
                'ordering': ['primer_apellido', 'segundo_apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EgresadoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='El archivo se guardará automáticamente en la carpeta del egresado', upload_to=titulacion.models.upload_path_egresado_documento)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titulacion.documento')),
                ('egresado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titulacion.egresado')),
            ],
            options={
                'verbose_name': 'Documento de Egresado',
                'verbose_name_plural': 'Documentos de Egresados',
                'unique_together': {('egresado', 'documento')},
            },
        ),
    ]
