# Generated by Django 5.2.1 on 2025-06-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='orden',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
