# Generated by Django 5.2.1 on 2025-06-09 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titulacion', '0002_etapa_orden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egresado',
            name='correo',
        ),
    ]
