# Generated by Django 5.2.1 on 2025-06-15 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulacion', '0004_egresado_etapa_alter_egresado_usuario_egresado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='extensiones_aceptados',
            field=models.CharField(default='pdf', help_text='Extensiones permitidas separadas por comas (ej: pdf,doc,docx,jpg,png)', max_length=200),
        ),
    ]
