# Generated by Django 5.2.1 on 2025-06-17 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titulacion', '0005_alter_documento_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='egresado',
            old_name='usuario_egresado',
            new_name='usuario',
        ),
    ]
