# Generated by Django 5.2.1 on 2025-06-18 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titulacion', '0006_rename_usuario_egresado_egresado_usuario'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='egresadodocumento',
            unique_together=set(),
        ),
    ]
