# Generated by Django 5.2.1 on 2025-06-19 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titulacion', '0007_alter_egresadodocumento_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
