# Generated by Django 5.2.1 on 2025-06-19 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulacion', '0008_rename_nombre_documento_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='clave',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
