# Generated by Django 5.2.1 on 2025-06-30 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulacion', '0009_documento_clave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresadodocumento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('revisado', 'Revisado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
    ]
