# Generated by Django 5.2.1 on 2025-10-07 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulacion', '0010_alter_egresadodocumento_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Grupo de Planes de Titulacion',
            },
        ),
        migrations.CreateModel(
            name='OpcionTitulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Opciones de Titulacion',
            },
        ),
        migrations.AddField(
            model_name='egresado',
            name='grupo_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='titulacion.grupoplan'),
        ),
        migrations.AddField(
            model_name='egresado',
            name='opcion_titulacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='titulacion.opciontitulacion'),
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='titulacion.grupoplan')),
            ],
            options={
                'verbose_name_plural': 'Planes de Titulacion',
            },
        ),
    ]
