# Generated by Django 5.2.1 on 2025-10-07 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulacion', '0011_grupoplan_opciontitulacion_egresado_grupo_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresado',
            name='grupo_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='titulacion.grupoplan'),
        ),
        migrations.AlterField(
            model_name='egresado',
            name='opcion_titulacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='titulacion.opciontitulacion'),
        ),
        migrations.AlterField(
            model_name='opciontitulacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='titulacion.grupoplan'),
        ),
    ]
