# Generated by Django 5.2.1 on 2025-10-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulacion', '0012_alter_egresado_grupo_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa',
            name='titulo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
