# Generated by Django 5.2.1 on 2025-12-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulacion', '0013_etapa_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresado',
            name='ano_de_egreso',
            field=models.IntegerField(blank=True, help_text='Año en que finalizó los estudios (ej: 2024)', null=True, verbose_name='Año de Egreso'),
        ),
        migrations.AddField(
            model_name='egresado',
            name='periodo_escolar_de_egreso',
            field=models.CharField(blank=True, choices=[('1', 'Enero - Junio'), ('2', 'Agosto - Diciembre')], max_length=1, null=True, verbose_name='Período de Egreso'),
        ),
    ]
